import React,{useState} from 'react';
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { Ionicons } from '@expo/vector-icons'; import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '../navigation'; import { colors } from '../theme/colors';
type Props=NativeStackScreenProps<RootStackParamList,'Boxes'>; type Filter='All'|'Connected'|'Attention'|'Inactive';
const people=[
{id:'ADMO-01',name:'Alexandra Popescu',age:'67',note:"Please make sure I take my evening medication after dinner.",status:'Connected',next:'08:00'},
{id:'ADMO-02',name:'Maria Ionescu',age:'72',note:'',status:'Connected',next:'08:30'},
{id:'ADMO-03',name:'Ion Popescu',age:'70',note:'Needs assistance with evening medication.',status:'Attention',next:'1 missed dose'},
{id:'ADMO-04',name:'Elena Dumitrescu',age:'64',note:'',status:'Connected',next:'09:00'}];
export function BoxesScreen({navigation}:Props){const[filter,setFilter]=useState<Filter>('All');const[q,setQ]=useState('');const visible=people.filter(p=>(filter==='All'||(filter==='Connected'&&p.status==='Connected')||(filter==='Attention'&&p.status==='Attention')||(filter==='Inactive'&&p.status==='Inactive'))&&p.name.toLowerCase().includes(q.toLowerCase()));
return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.head}><Pressable onPress={()=>navigation.goBack()}><Ionicons name="arrow-back" size={25} color={colors.navy}/></Pressable><View style={{flex:1}}><Text style={s.title}>ADMO Boxes</Text><Text style={s.sub}>Manage all boxes connected to your account.</Text></View></View>
<View style={s.search}><Ionicons name="search-outline" size={19} color="#7890B1"/><TextInput value={q} onChangeText={setQ} placeholder="Search users..." placeholderTextColor="#93A3BA" style={s.input}/></View>
<View style={s.filters}>{(['All','Connected','Attention','Inactive'] as Filter[]).map(x=><Pressable key={x} style={[s.filter,filter===x&&s.filterOn]} onPress={()=>setFilter(x)}><Text style={[s.ft,filter===x&&s.ftOn]}>{x}</Text></Pressable>)}</View>
<Text style={s.label}>Box users ({visible.length})</Text><View style={{gap:10}}>{visible.map((p,i)=><Pressable key={p.id} style={s.card} onPress={()=>navigation.navigate('BoxProfile',p)}><View style={[s.avatar,p.status==='Attention'&&{backgroundColor:'#FFF0E8'}]}><Text style={s.initials}>{p.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</Text></View><View style={{flex:1}}><Text style={s.name}>{p.name}</Text><View style={s.meta}><Text style={s.id}>{p.id}</Text><Text style={p.status==='Attention'?s.attention:s.connected}>● {p.status==='Attention'?'Attention needed':'Connected'}</Text></View><Text style={s.next}>{p.status==='Attention'?'⚠ ': '◷ '} {p.next}</Text></View><Pressable style={s.more} onPress={()=>{}}><Ionicons name="ellipsis-vertical" size={19} color={colors.navy}/></Pressable><Ionicons name="chevron-forward" size={18} color="#7890B1"/></Pressable>)}</View>
<Pressable style={s.add} onPress={()=>navigation.navigate('ConnectBox')}><Text style={s.addText}>＋  Add new user / ADMO Box</Text></Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fff'},content:{padding:22,paddingBottom:34,backgroundColor:'#F9FEFF',flexGrow:1},head:{flexDirection:'row',gap:14,alignItems:'center',marginTop:8},title:{fontSize:25,fontWeight:'800',color:colors.navy},sub:{fontSize:11,color:'#7A90AF',marginTop:3},search:{height:48,borderWidth:1,borderColor:'#DFE8ED',borderRadius:12,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:8,marginTop:22},input:{flex:1,fontSize:14,color:colors.navy},filters:{flexDirection:'row',gap:7,marginTop:14},filter:{flex:1,minHeight:36,borderRadius:9,borderWidth:1,borderColor:'#E2EAEE',alignItems:'center',justifyContent:'center',paddingHorizontal:4},filterOn:{backgroundColor:colors.teal,borderColor:colors.teal},ft:{fontSize:9,color:'#7287A7'},ftOn:{color:'#fff',fontWeight:'700'},label:{fontSize:12,fontWeight:'800',color:colors.navy,marginTop:24,marginBottom:10},card:{minHeight:92,borderRadius:14,borderWidth:1,borderColor:'#E4ECEF',backgroundColor:'#fff',padding:12,flexDirection:'row',alignItems:'center',gap:10},avatar:{width:48,height:48,borderRadius:24,backgroundColor:'#E1F5F3',alignItems:'center',justifyContent:'center'},initials:{color:colors.teal,fontSize:17,fontWeight:'800'},name:{fontSize:13,fontWeight:'800',color:colors.navy},meta:{flexDirection:'row',gap:9,marginTop:4},id:{fontSize:10,color:'#7186A5'},connected:{fontSize:10,color:'#0AA66F'},attention:{fontSize:10,color:'#E77931'},next:{fontSize:10,color:'#7186A5',marginTop:8},more:{width:30,height:38,alignItems:'center',justifyContent:'center'},add:{height:52,borderRadius:13,borderWidth:1,borderStyle:'dashed',borderColor:colors.teal,alignItems:'center',justifyContent:'center',marginTop:20},addText:{color:colors.teal,fontWeight:'700',fontSize:13}});
